# PHPMetrics configuration for OpenFGA PHP SDK
# Generates comprehensive metrics reports to identify refactoring opportunities

includes:
    - ./src

excludes:
    - ./tests
    - ./vendor
    - ./examples
    - ./tools
    - ./docs

report:
    html: ./build/metrics/
    json: ./build/metrics.json
    csv: ./build/metrics.csv
    
# Metric thresholds for identifying problematic code
rules:
    # Cyclomatic Complexity: Number of independent paths through code
    cyclomaticComplexity:
        critical: 10  # Red flag - needs immediate refactoring
        warning: 7    # Yellow flag - consider refactoring
    
    # Maintainability Index: 0-100 scale (higher is better)
    maintainabilityIndex:
        critical: 65  # Below this is hard to maintain
        warning: 85   # Below this needs attention
    
    # Halstead metrics measure program complexity
    halstead:
        # Difficulty: How hard the code is to understand
        difficulty:
            critical: 30
            warning: 20
        # Volume: Size of the implementation
        volume:
            critical: 8000
            warning: 4000
        # Effort: Mental effort to understand the code
        effort:
            critical: 1000000
            warning: 500000
    
    # Lines of Code per method
    loc:
        method:
            critical: 50
            warning: 30
        class:
            critical: 500
            warning: 300
    
    # Coupling metrics
    coupling:
        afferent:  # Classes that depend on this class
            critical: 20
            warning: 10
        efferent:  # Classes this class depends on
            critical: 20
            warning: 10
    
    # Lack of Cohesion of Methods (LCOM)
    # Lower values indicate better cohesion
    lcom:
        critical: 4
        warning: 2

# Chart configurations for HTML report
charts:
    bubbleChart:
        enabled: true
        title: "Complexity vs Size"
    
    violations:
        enabled: true
        
# Additional analysis options
analysis:
    # Include git history for trend analysis
    git:
        enabled: false  # Enable if you want historical metrics
        
    # Group metrics by namespace
    groups:
        - name: "Authentication"
          match: "OpenFGA\\Authentication\\*"
        - name: "Models"
          match: "OpenFGA\\Models\\*"
        - name: "Network"
          match: "OpenFGA\\Network\\*"
        - name: "Requests/Responses"
          match: "OpenFGA\\(Requests|Responses)\\*"