version: '3.8'
services:
  openfga:
    image: openfga/openfga:latest
    command: run
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
