name: Bug Report
description: Something not working? Let us know!
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        👋 Thanks for helping us improve! We'll get this sorted.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us about the bug
      placeholder: When I try to check permissions, the client throws...
    validations:
      required: true

  - type: textarea
    id: show-me
    attributes:
      label: Show me the code
      description: A minimal example that reproduces the issue
      placeholder: |
        ```php
        $client = new OpenFGA\Client(/* ... */);
        // Your code here
        ```
      render: php
    validations:
      required: true

  - type: textarea
    id: expected-vs-actual
    attributes:
      label: Expected vs Actual
      description: What should happen vs what does happen?
      placeholder: |
        Expected: Returns true
        Actual: Throws ValidationException
    validations:
      required: true

  - type: input
    id: versions
    attributes:
      label: Environment
      description: PHP and library versions (e.g., "PHP 8.3, openfga-php 1.0.0")
      placeholder: PHP 8.3, openfga-php 1.0.0
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Anything else?
      description: Additional context, error logs, server info, etc.
    validations:
      required: false