name: Feature Request
description: Have an idea? We'd love to hear it!
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        💡 Great ideas make great libraries. Thanks for sharing yours!

  - type: textarea
    id: the-pitch
    attributes:
      label: The pitch
      description: What would you like to see added?
      placeholder: It would be awesome if the library could...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: My use case
      description: How would this help you? Show us with code!
      placeholder: |
        ```php
        // I'd use it like this:
        $client->amazingNewFeature();
        ```
      render: php
    validations:
      required: true

  - type: textarea
    id: workarounds
    attributes:
      label: Current workarounds
      description: How are you solving this today? (optional)
      placeholder: Right now I have to...
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        💭 **Note:** If this needs OpenFGA API changes, please mention it above!