<?php

declare(strict_types=1);
/**
 * ErrorCode.
 *
 * PHP version 7.4
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * OpenFGA.
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 1.x
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenFGA\API\Model;

/**
 * ErrorCode Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */
final class ErrorCode
{
    public const ASSERTIONS_TOO_MANY_ITEMS = 'assertions_too_many_items';

    public const AUTHORIZATION_MODEL_ASSERTIONS_NOT_FOUND = 'authorization_model_assertions_not_found';

    public const AUTHORIZATION_MODEL_ID_TOO_LONG = 'authorization_model_id_too_long';

    public const AUTHORIZATION_MODEL_NOT_FOUND = 'authorization_model_not_found';

    public const AUTHORIZATION_MODEL_RESOLUTION_TOO_COMPLEX = 'authorization_model_resolution_too_complex';

    public const CANCELLED = 'cancelled';

    public const CANNOT_ALLOW_DUPLICATE_TUPLES_IN_ONE_REQUEST = 'cannot_allow_duplicate_tuples_in_one_request';

    public const CANNOT_ALLOW_DUPLICATE_TYPES_IN_ONE_REQUEST = 'cannot_allow_duplicate_types_in_one_request';

    public const CANNOT_ALLOW_MULTIPLE_REFERENCES_TO_ONE_RELATION = 'cannot_allow_multiple_references_to_one_relation';

    public const DIFFERENCE_BASE_MISSING_VALUE = 'difference_base_missing_value';

    public const DUPLICATE_CONTEXTUAL_TUPLE = 'duplicate_contextual_tuple';

    public const EMPTY_RELATION_DEFINITION = 'empty_relation_definition';

    public const EXCEEDED_ENTITY_LIMIT = 'exceeded_entity_limit';

    public const ID_TOO_LONG = 'id_too_long';

    public const INVALID_AUTHORIZATION_MODEL = 'invalid_authorization_model';

    public const INVALID_CHECK_INPUT = 'invalid_check_input';

    public const INVALID_CONTEXTUAL_TUPLE = 'invalid_contextual_tuple';

    public const INVALID_CONTINUATION_TOKEN = 'invalid_continuation_token';

    public const INVALID_EXPAND_INPUT = 'invalid_expand_input';

    public const INVALID_OBJECT_FORMAT = 'invalid_object_format';

    public const INVALID_TUPLE = 'invalid_tuple';

    public const INVALID_TUPLE_SET = 'invalid_tuple_set';

    public const INVALID_USER = 'invalid_user';

    public const INVALID_WRITE_INPUT = 'invalid_write_input';

    public const LATEST_AUTHORIZATION_MODEL_NOT_FOUND = 'latest_authorization_model_not_found';

    /**
     * Possible values of this enum.
     */
    public const NO_ERROR = 'no_error';

    public const OBJECT_INVALID_PATTERN = 'object_invalid_pattern';

    public const OBJECT_TOO_LONG = 'object_too_long';

    public const PAGE_SIZE_INVALID = 'page_size_invalid';

    public const PARAM_MISSING_VALUE = 'param_missing_value';

    public const QUERY_STRING_TYPE_CONTINUATION_TOKEN_MISMATCH = 'query_string_type_continuation_token_mismatch';

    public const RELATION_NOT_FOUND = 'relation_not_found';

    public const RELATION_TOO_LONG = 'relation_too_long';

    public const RELATIONS_INVALID_PATTERN = 'relations_invalid_pattern';

    public const RELATIONS_TOO_FEW_ITEMS = 'relations_too_few_items';

    public const RELATIONS_TOO_LONG = 'relations_too_long';

    public const STORE_ID_INVALID_LENGTH = 'store_id_invalid_length';

    public const SUBTRACT_BASE_MISSING_VALUE = 'subtract_base_missing_value';

    public const TUPLE_KEY_VALUE_NOT_SPECIFIED = 'tuple_key_value_not_specified';

    public const TUPLE_KEYS_TOO_MANY_OR_TOO_FEW_ITEMS = 'tuple_keys_too_many_or_too_few_items';

    public const TYPE_DEFINITIONS_TOO_FEW_ITEMS = 'type_definitions_too_few_items';

    public const TYPE_INVALID_LENGTH = 'type_invalid_length';

    public const TYPE_INVALID_PATTERN = 'type_invalid_pattern';

    public const TYPE_NOT_FOUND = 'type_not_found';

    public const UNKNOWN_RELATION = 'unknown_relation';

    public const UNSUPPORTED_SCHEMA_VERSION = 'unsupported_schema_version';

    public const UNSUPPORTED_USER_SET = 'unsupported_user_set';

    public const VALIDATION_ERROR = 'validation_error';

    public const WRITE_FAILED_DUE_TO_INVALID_INPUT = 'write_failed_due_to_invalid_input';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NO_ERROR,
            self::VALIDATION_ERROR,
            self::AUTHORIZATION_MODEL_NOT_FOUND,
            self::AUTHORIZATION_MODEL_RESOLUTION_TOO_COMPLEX,
            self::INVALID_WRITE_INPUT,
            self::CANNOT_ALLOW_DUPLICATE_TUPLES_IN_ONE_REQUEST,
            self::CANNOT_ALLOW_DUPLICATE_TYPES_IN_ONE_REQUEST,
            self::CANNOT_ALLOW_MULTIPLE_REFERENCES_TO_ONE_RELATION,
            self::INVALID_CONTINUATION_TOKEN,
            self::INVALID_TUPLE_SET,
            self::INVALID_CHECK_INPUT,
            self::INVALID_EXPAND_INPUT,
            self::UNSUPPORTED_USER_SET,
            self::INVALID_OBJECT_FORMAT,
            self::WRITE_FAILED_DUE_TO_INVALID_INPUT,
            self::AUTHORIZATION_MODEL_ASSERTIONS_NOT_FOUND,
            self::LATEST_AUTHORIZATION_MODEL_NOT_FOUND,
            self::TYPE_NOT_FOUND,
            self::RELATION_NOT_FOUND,
            self::EMPTY_RELATION_DEFINITION,
            self::INVALID_USER,
            self::INVALID_TUPLE,
            self::UNKNOWN_RELATION,
            self::STORE_ID_INVALID_LENGTH,
            self::ASSERTIONS_TOO_MANY_ITEMS,
            self::ID_TOO_LONG,
            self::AUTHORIZATION_MODEL_ID_TOO_LONG,
            self::TUPLE_KEY_VALUE_NOT_SPECIFIED,
            self::TUPLE_KEYS_TOO_MANY_OR_TOO_FEW_ITEMS,
            self::PAGE_SIZE_INVALID,
            self::PARAM_MISSING_VALUE,
            self::DIFFERENCE_BASE_MISSING_VALUE,
            self::SUBTRACT_BASE_MISSING_VALUE,
            self::OBJECT_TOO_LONG,
            self::RELATION_TOO_LONG,
            self::TYPE_DEFINITIONS_TOO_FEW_ITEMS,
            self::TYPE_INVALID_LENGTH,
            self::TYPE_INVALID_PATTERN,
            self::RELATIONS_TOO_FEW_ITEMS,
            self::RELATIONS_TOO_LONG,
            self::RELATIONS_INVALID_PATTERN,
            self::OBJECT_INVALID_PATTERN,
            self::QUERY_STRING_TYPE_CONTINUATION_TOKEN_MISMATCH,
            self::EXCEEDED_ENTITY_LIMIT,
            self::INVALID_CONTEXTUAL_TUPLE,
            self::DUPLICATE_CONTEXTUAL_TUPLE,
            self::INVALID_AUTHORIZATION_MODEL,
            self::UNSUPPORTED_SCHEMA_VERSION,
            self::CANCELLED,
        ];
    }
}
