<?php

declare(strict_types=1);
/**
 * ListUsersRequest.
 *
 * PHP version 7.4
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * OpenFGA.
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 1.x
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenFGA\API\Model;

use ArrayAccess;
use InvalidArgumentException;
use JsonSerializable;
use OpenFGA\API\ObjectSerializer;
use ReturnTypeWillChange;

use function array_key_exists;
use function count;
use function in_array;

/**
 * ListUsersRequest Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 *
 * @implements \ArrayAccess<string, mixed>
 */
final class ListUsersRequest implements ArrayAccess, JsonSerializable, ModelInterface
{
    public const DISCRIMINATOR = null;

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    private $container = [];

    /**
     * If a nullable field gets set to null, insert it here.
     *
     * @var bool[]
     */
    private array $openAPINullablesSetToNull = [];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    private static $attributeMap = [
        'authorizationModelId' => 'authorization_model_id',
        'object' => 'object',
        'relation' => 'relation',
        'userFilters' => 'user_filters',
        'contextualTuples' => 'contextual_tuples',
        'context' => 'context',
        'consistency' => 'consistency',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    private static $getters = [
        'authorizationModelId' => 'getAuthorizationModelId',
        'object' => 'getObject',
        'relation' => 'getRelation',
        'userFilters' => 'getUserFilters',
        'contextualTuples' => 'getContextualTuples',
        'context' => 'getContext',
        'consistency' => 'getConsistency',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    private static $openAPIFormats = [
        'authorizationModelId' => null,
        'object' => null,
        'relation' => null,
        'userFilters' => null,
        'contextualTuples' => null,
        'context' => null,
        'consistency' => null,
    ];

    /**
     * The original name of the model.
     *
     * @var string
     */
    private static $openAPIModelName = 'ListUsers_request';

    /**
     * Array of nullable properties. Used for (de)serialization.
     *
     * @var bool[]
     */
    private static array $openAPINullables = [
        'authorizationModelId' => false,
        'object' => false,
        'relation' => false,
        'userFilters' => false,
        'contextualTuples' => false,
        'context' => false,
        'consistency' => false,
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    private static $openAPITypes = [
        'authorizationModelId' => 'string',
        'object' => '\OpenFGA\API\Model\Object',
        'relation' => 'string',
        'userFilters' => '\OpenFGA\API\Model\UserTypeFilter[]',
        'contextualTuples' => '\OpenFGA\API\Model\TupleKey[]',
        'context' => 'object',
        'consistency' => '\OpenFGA\API\Model\ConsistencyPreference',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    private static $setters = [
        'authorizationModelId' => 'setAuthorizationModelId',
        'object' => 'setObject',
        'relation' => 'setRelation',
        'userFilters' => 'setUserFilters',
        'contextualTuples' => 'setContextualTuples',
        'context' => 'setContext',
        'consistency' => 'setConsistency',
    ];

    /**
     * Constructor.
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('authorizationModelId', $data ?? [], null);
        $this->setIfExists('object', $data ?? [], null);
        $this->setIfExists('relation', $data ?? [], null);
        $this->setIfExists('userFilters', $data ?? [], null);
        $this->setIfExists('contextualTuples', $data ?? [], null);
        $this->setIfExists('context', $data ?? [], null);
        $this->setIfExists('consistency', $data ?? [], null);
    }

    /**
     * Gets the string presentation of the object.
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT,
        );
    }

    /**
     * Gets authorizationModelId.
     *
     * @return null|string
     */
    public function getAuthorizationModelId()
    {
        return $this->container['authorizationModelId'];
    }

    /**
     * Gets consistency.
     *
     * @return null|ConsistencyPreference
     */
    public function getConsistency()
    {
        return $this->container['consistency'];
    }

    /**
     * Gets context.
     *
     * @return null|object
     */
    public function getContext()
    {
        return $this->container['context'];
    }

    /**
     * Gets contextualTuples.
     *
     * @return null|TupleKey[]
     */
    public function getContextualTuples()
    {
        return $this->container['contextualTuples'];
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    /**
     * Gets object.
     *
     * @return \OpenFGA\API\Model\Object
     */
    public function getObject()
    {
        return $this->container['object'];
    }

    /**
     * Gets relation.
     *
     * @return string
     */
    public function getRelation()
    {
        return $this->container['relation'];
    }

    /**
     * Gets userFilters.
     *
     * @return UserTypeFilter[]
     */
    public function getUserFilters()
    {
        return $this->container['userFilters'];
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     *
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (null === $this->container['object']) {
            $invalidProperties[] = "'object' can't be null";
        }
        if (null === $this->container['relation']) {
            $invalidProperties[] = "'relation' can't be null";
        }
        if (null === $this->container['userFilters']) {
            $invalidProperties[] = "'userFilters' can't be null";
        }
        if ((count($this->container['userFilters']) > 1)) {
            $invalidProperties[] = "invalid value for 'userFilters', number of items must be less than or equal to 1.";
        }

        if ((count($this->container['userFilters']) < 1)) {
            $invalidProperties[] = "invalid value for 'userFilters', number of items must be greater than or equal to 1.";
        }

        if (null !== $this->container['contextualTuples'] && (count($this->container['contextualTuples']) > 100)) {
            $invalidProperties[] = "invalid value for 'contextualTuples', number of items must be less than or equal to 100.";
        }

        return $invalidProperties;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     *
     * @return bool
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return null|mixed
     */
    #[ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param null|int $offset Offset
     * @param mixed    $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (null === $offset) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Sets authorizationModelId.
     *
     * @param null|string $authorizationModelId authorizationModelId
     *
     * @return self
     */
    public function setAuthorizationModelId($authorizationModelId)
    {
        if (null === $authorizationModelId) {
            throw new InvalidArgumentException('non-nullable authorizationModelId cannot be null');
        }
        $this->container['authorizationModelId'] = $authorizationModelId;

        return $this;
    }

    /**
     * Sets consistency.
     *
     * @param null|ConsistencyPreference $consistency consistency
     *
     * @return self
     */
    public function setConsistency($consistency)
    {
        if (null === $consistency) {
            throw new InvalidArgumentException('non-nullable consistency cannot be null');
        }
        $this->container['consistency'] = $consistency;

        return $this;
    }

    /**
     * Sets context.
     *
     * @param null|object $context Additional request context that will be used to evaluate any ABAC conditions encountered in the query evaluation.
     *
     * @return self
     */
    public function setContext($context)
    {
        if (null === $context) {
            throw new InvalidArgumentException('non-nullable context cannot be null');
        }
        $this->container['context'] = $context;

        return $this;
    }

    /**
     * Sets contextualTuples.
     *
     * @param null|TupleKey[] $contextualTuples contextualTuples
     *
     * @return self
     */
    public function setContextualTuples($contextualTuples)
    {
        if (null === $contextualTuples) {
            throw new InvalidArgumentException('non-nullable contextualTuples cannot be null');
        }

        if ((count($contextualTuples) > 100)) {
            throw new InvalidArgumentException('invalid value for $contextualTuples when calling ListUsersRequest., number of items must be less than or equal to 100.');
        }
        $this->container['contextualTuples'] = $contextualTuples;

        return $this;
    }

    /**
     * Sets object.
     *
     * @param \OpenFGA\API\Model\Object $object object
     *
     * @return self
     */
    public function setObject($object)
    {
        if (null === $object) {
            throw new InvalidArgumentException('non-nullable object cannot be null');
        }
        $this->container['object'] = $object;

        return $this;
    }

    /**
     * Sets relation.
     *
     * @param string $relation relation
     *
     * @return self
     */
    public function setRelation($relation)
    {
        if (null === $relation) {
            throw new InvalidArgumentException('non-nullable relation cannot be null');
        }
        $this->container['relation'] = $relation;

        return $this;
    }

    /**
     * Sets userFilters.
     *
     * @param UserTypeFilter[] $userFilters The type of results returned. Only accepts exactly one value.
     *
     * @return self
     */
    public function setUserFilters($userFilters)
    {
        if (null === $userFilters) {
            throw new InvalidArgumentException('non-nullable userFilters cannot be null');
        }

        if ((count($userFilters) > 1)) {
            throw new InvalidArgumentException('invalid value for $userFilters when calling ListUsersRequest., number of items must be less than or equal to 1.');
        }
        if ((count($userFilters) < 1)) {
            throw new InvalidArgumentException('invalid length for $userFilters when calling ListUsersRequest., number of items must be greater than or equal to 1.');
        }
        $this->container['userFilters'] = $userFilters;

        return $this;
    }

    /**
     * Gets a header-safe presentation of the object.
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return 0 === count($this->listInvalidProperties());
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * Checks if a property is nullable.
     *
     * @param string $property
     *
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of nullable field names deliberately set to null.
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array.
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && null === $fields[$variableName]) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null.
     *
     * @param bool[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Array of nullable properties.
     *
     * @return array
     */
    private static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }
}
