<?php

declare(strict_types=1);
/**
 * RelationshipQueriesApi
 * PHP version 7.2.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * OpenFGA.
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 1.x
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenFGA\API\Api;

use GuzzleHttp\Psr7\MultipartStream;
use Http\Client\Common\Plugin\{ErrorPlugin, RedirectPlugin};
use Http\Client\Common\{PluginClient, PluginClientFactory};
use Http\Client\Exception\HttpException;
use Http\Client\HttpAsyncClient;
use Http\Discovery\{HttpAsyncClientDiscovery, Psr17FactoryDiscovery, Psr18ClientDiscovery};
use Http\Message\RequestFactory;
use Http\Promise\Promise;
use InvalidArgumentException;
use OpenFGA\API\{ApiException, Configuration, DebugPlugin, HeaderSelector, ObjectSerializer};
use Psr\Http\Client\{ClientExceptionInterface, ClientInterface};
use Psr\Http\Message\{RequestFactoryInterface, RequestInterface, StreamFactoryInterface, UriFactoryInterface, UriInterface};
use RuntimeException;

use function count;
use function is_array;
use function is_string;
use function sprintf;

/**
 * RelationshipQueriesApi Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */
final class RelationshipQueriesApi
{
    /**
     * @var Configuration
     */
    private $config;

    /**
     * @var HeaderSelector
     */
    private $headerSelector;

    /**
     * @var int Host index
     */
    private $hostIndex;

    /**
     * @var PluginClient
     */
    private $httpAsyncClient;

    /**
     * @var PluginClient
     */
    private $httpClient;

    /**
     * @var RequestFactoryInterface
     */
    private $requestFactory;

    /**
     * @var StreamFactoryInterface
     */
    private $streamFactory;

    /**
     * @var UriFactoryInterface
     */
    private $uriFactory;

    public function __construct(
        ?ClientInterface $httpClient = null,
        ?Configuration $config = null,
        ?HttpAsyncClient $httpAsyncClient = null,
        ?UriFactoryInterface $uriFactory = null,
        ?RequestFactoryInterface $requestFactory = null,
        ?StreamFactoryInterface $streamFactory = null,
        ?HeaderSelector $selector = null,
        ?array $plugins = null,
        $hostIndex = 0,
    ) {
        $this->config = $config ?? (new Configuration())->setHost('http://localhost');
        $this->requestFactory = $requestFactory ?? Psr17FactoryDiscovery::findRequestFactory();
        $this->streamFactory = $streamFactory ?? Psr17FactoryDiscovery::findStreamFactory();

        $plugins ??= [
            new RedirectPlugin(['strict' => true]),
            new ErrorPlugin(),
        ];

        if ($this->config->getDebug()) {
            $plugins[] = new DebugPlugin(fopen($this->config->getDebugFile(), 'ab'));
        }

        $this->httpClient = (new PluginClientFactory())->createClient(
            $httpClient ?? Psr18ClientDiscovery::find(),
            $plugins,
        );

        $this->httpAsyncClient = (new PluginClientFactory())->createClient(
            $httpAsyncClient ?? HttpAsyncClientDiscovery::find(),
            $plugins,
        );

        $this->uriFactory = $uriFactory ?? Psr17FactoryDiscovery::findUriFactory();

        $this->headerSelector = $selector ?? new HeaderSelector();

        $this->hostIndex = $hostIndex;
    }

    /**
     * Operation check.
     *
     * Check whether a user is authorized to access an object
     *
     * @param string                          $storeId storeId (required)
     * @param \OpenFGA\API\Model\CheckRequest $body    body (required)
     *
     * @throws ApiException             on non-2xx response
     * @throws InvalidArgumentException
     *
     * @return \OpenFGA\API\Model\AbortedMessageResponse|\OpenFGA\API\Model\CheckResponse|\OpenFGA\API\Model\ForbiddenResponse|\OpenFGA\API\Model\InternalErrorMessageResponse|\OpenFGA\API\Model\PathUnknownErrorMessageResponse|\OpenFGA\API\Model\UnauthenticatedResponse|\OpenFGA\API\Model\UnprocessableContentMessageResponse|\OpenFGA\API\Model\ValidationErrorMessageResponse
     */
    public function check($storeId, $body)
    {
        [$response] = $this->checkWithHttpInfo($storeId, $body);

        return $response;
    }

    /**
     * Operation checkAsync.
     *
     * Check whether a user is authorized to access an object
     *
     * @param string                          $storeId (required)
     * @param \OpenFGA\API\Model\CheckRequest $body    (required)
     *
     * @throws InvalidArgumentException
     *
     * @return Promise
     */
    public function checkAsync($storeId, $body)
    {
        return $this->checkAsyncWithHttpInfo($storeId, $body)
            ->then(
                static fn ($response) => $response[0],
            );
    }

    /**
     * Operation checkAsyncWithHttpInfo.
     *
     * Check whether a user is authorized to access an object
     *
     * @param string                          $storeId (required)
     * @param \OpenFGA\API\Model\CheckRequest $body    (required)
     *
     * @throws InvalidArgumentException
     *
     * @return Promise
     */
    public function checkAsyncWithHttpInfo($storeId, $body)
    {
        $returnType = '\OpenFGA\API\Model\CheckResponse';
        $request = $this->checkRequest($storeId, $body);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                static function ($response) use ($returnType) {
                    if ('\SplFileObject' === $returnType) {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                static function (HttpException $exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $exception->getRequest(), $exception->getResponse(), $exception);
                },
            );
    }

    /**
     * Create request for operation 'check'.
     *
     * @param string                          $storeId (required)
     * @param \OpenFGA\API\Model\CheckRequest $body    (required)
     *
     * @throws InvalidArgumentException
     *
     * @return RequestInterface
     */
    public function checkRequest($storeId, $body)
    {
        // verify the required parameter 'storeId' is set
        if (null === $storeId || (is_array($storeId) && 0 === count($storeId))) {
            throw new InvalidArgumentException('Missing the required parameter $storeId when calling check');
        }
        // verify the required parameter 'body' is set
        if (null === $body || (is_array($body) && 0 === count($body))) {
            throw new InvalidArgumentException('Missing the required parameter $body when calling check');
        }

        $resourcePath = '/stores/{store_id}/check';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // path params
        if (null !== $storeId) {
            $resourcePath = str_replace(
                '{store_id}',
                ObjectSerializer::toPathValue($storeId),
                $resourcePath,
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart,
        );

        // for model (json/xml)
        if (isset($body)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers,
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('POST', $uri, $headers, $httpBody);
    }

    /**
     * Operation checkWithHttpInfo.
     *
     * Check whether a user is authorized to access an object
     *
     * @param string                          $storeId (required)
     * @param \OpenFGA\API\Model\CheckRequest $body    (required)
     *
     * @throws ApiException             on non-2xx response
     * @throws InvalidArgumentException
     *
     * @return array of \OpenFGA\API\Model\CheckResponse|\OpenFGA\API\Model\ValidationErrorMessageResponse|\OpenFGA\API\Model\UnauthenticatedResponse|\OpenFGA\API\Model\ForbiddenResponse|\OpenFGA\API\Model\PathUnknownErrorMessageResponse|\OpenFGA\API\Model\AbortedMessageResponse|\OpenFGA\API\Model\UnprocessableContentMessageResponse|\OpenFGA\API\Model\InternalErrorMessageResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function checkWithHttpInfo($storeId, $body)
    {
        $request = $this->checkRequest($storeId, $body);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();

                throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $response->getStatusCode(), (string) $request->getUri()), $request, $response, $e);
            } catch (ClientExceptionInterface $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", $request, null, $e);
            }

            $statusCode = $response->getStatusCode();

            switch ($statusCode) {
                case 200:
                    if ('\OpenFGA\API\Model\CheckResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\CheckResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 400:
                    if ('\OpenFGA\API\Model\ValidationErrorMessageResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\ValidationErrorMessageResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 401:
                    if ('\OpenFGA\API\Model\UnauthenticatedResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\UnauthenticatedResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 403:
                    if ('\OpenFGA\API\Model\ForbiddenResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\ForbiddenResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 404:
                    if ('\OpenFGA\API\Model\PathUnknownErrorMessageResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\PathUnknownErrorMessageResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 409:
                    if ('\OpenFGA\API\Model\AbortedMessageResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\AbortedMessageResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 422:
                    if ('\OpenFGA\API\Model\UnprocessableContentMessageResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\UnprocessableContentMessageResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 500:
                    if ('\OpenFGA\API\Model\InternalErrorMessageResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\InternalErrorMessageResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
            }

            $returnType = '\OpenFGA\API\Model\CheckResponse';
            if ('\SplFileObject' === $returnType) {
                $content = $response->getBody(); // stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\CheckResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\ValidationErrorMessageResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\UnauthenticatedResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\ForbiddenResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\PathUnknownErrorMessageResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\AbortedMessageResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\UnprocessableContentMessageResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\InternalErrorMessageResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation expand.
     *
     * Expand all relationships in userset tree format, and following userset rewrite rules.  Useful to reason about and debug a certain relationship
     *
     * @param string                           $storeId storeId (required)
     * @param \OpenFGA\API\Model\ExpandRequest $body    body (required)
     *
     * @throws ApiException             on non-2xx response
     * @throws InvalidArgumentException
     *
     * @return \OpenFGA\API\Model\AbortedMessageResponse|\OpenFGA\API\Model\ExpandResponse|\OpenFGA\API\Model\ForbiddenResponse|\OpenFGA\API\Model\InternalErrorMessageResponse|\OpenFGA\API\Model\PathUnknownErrorMessageResponse|\OpenFGA\API\Model\UnauthenticatedResponse|\OpenFGA\API\Model\UnprocessableContentMessageResponse|\OpenFGA\API\Model\ValidationErrorMessageResponse
     */
    public function expand($storeId, $body)
    {
        [$response] = $this->expandWithHttpInfo($storeId, $body);

        return $response;
    }

    /**
     * Operation expandAsync.
     *
     * Expand all relationships in userset tree format, and following userset rewrite rules.  Useful to reason about and debug a certain relationship
     *
     * @param string                           $storeId (required)
     * @param \OpenFGA\API\Model\ExpandRequest $body    (required)
     *
     * @throws InvalidArgumentException
     *
     * @return Promise
     */
    public function expandAsync($storeId, $body)
    {
        return $this->expandAsyncWithHttpInfo($storeId, $body)
            ->then(
                static fn ($response) => $response[0],
            );
    }

    /**
     * Operation expandAsyncWithHttpInfo.
     *
     * Expand all relationships in userset tree format, and following userset rewrite rules.  Useful to reason about and debug a certain relationship
     *
     * @param string                           $storeId (required)
     * @param \OpenFGA\API\Model\ExpandRequest $body    (required)
     *
     * @throws InvalidArgumentException
     *
     * @return Promise
     */
    public function expandAsyncWithHttpInfo($storeId, $body)
    {
        $returnType = '\OpenFGA\API\Model\ExpandResponse';
        $request = $this->expandRequest($storeId, $body);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                static function ($response) use ($returnType) {
                    if ('\SplFileObject' === $returnType) {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                static function (HttpException $exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $exception->getRequest(), $exception->getResponse(), $exception);
                },
            );
    }

    /**
     * Create request for operation 'expand'.
     *
     * @param string                           $storeId (required)
     * @param \OpenFGA\API\Model\ExpandRequest $body    (required)
     *
     * @throws InvalidArgumentException
     *
     * @return RequestInterface
     */
    public function expandRequest($storeId, $body)
    {
        // verify the required parameter 'storeId' is set
        if (null === $storeId || (is_array($storeId) && 0 === count($storeId))) {
            throw new InvalidArgumentException('Missing the required parameter $storeId when calling expand');
        }
        // verify the required parameter 'body' is set
        if (null === $body || (is_array($body) && 0 === count($body))) {
            throw new InvalidArgumentException('Missing the required parameter $body when calling expand');
        }

        $resourcePath = '/stores/{store_id}/expand';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // path params
        if (null !== $storeId) {
            $resourcePath = str_replace(
                '{store_id}',
                ObjectSerializer::toPathValue($storeId),
                $resourcePath,
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart,
        );

        // for model (json/xml)
        if (isset($body)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers,
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('POST', $uri, $headers, $httpBody);
    }

    /**
     * Operation expandWithHttpInfo.
     *
     * Expand all relationships in userset tree format, and following userset rewrite rules.  Useful to reason about and debug a certain relationship
     *
     * @param string                           $storeId (required)
     * @param \OpenFGA\API\Model\ExpandRequest $body    (required)
     *
     * @throws ApiException             on non-2xx response
     * @throws InvalidArgumentException
     *
     * @return array of \OpenFGA\API\Model\ExpandResponse|\OpenFGA\API\Model\ValidationErrorMessageResponse|\OpenFGA\API\Model\UnauthenticatedResponse|\OpenFGA\API\Model\ForbiddenResponse|\OpenFGA\API\Model\PathUnknownErrorMessageResponse|\OpenFGA\API\Model\AbortedMessageResponse|\OpenFGA\API\Model\UnprocessableContentMessageResponse|\OpenFGA\API\Model\InternalErrorMessageResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function expandWithHttpInfo($storeId, $body)
    {
        $request = $this->expandRequest($storeId, $body);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();

                throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $response->getStatusCode(), (string) $request->getUri()), $request, $response, $e);
            } catch (ClientExceptionInterface $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", $request, null, $e);
            }

            $statusCode = $response->getStatusCode();

            switch ($statusCode) {
                case 200:
                    if ('\OpenFGA\API\Model\ExpandResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\ExpandResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 400:
                    if ('\OpenFGA\API\Model\ValidationErrorMessageResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\ValidationErrorMessageResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 401:
                    if ('\OpenFGA\API\Model\UnauthenticatedResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\UnauthenticatedResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 403:
                    if ('\OpenFGA\API\Model\ForbiddenResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\ForbiddenResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 404:
                    if ('\OpenFGA\API\Model\PathUnknownErrorMessageResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\PathUnknownErrorMessageResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 409:
                    if ('\OpenFGA\API\Model\AbortedMessageResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\AbortedMessageResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 422:
                    if ('\OpenFGA\API\Model\UnprocessableContentMessageResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\UnprocessableContentMessageResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 500:
                    if ('\OpenFGA\API\Model\InternalErrorMessageResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\InternalErrorMessageResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
            }

            $returnType = '\OpenFGA\API\Model\ExpandResponse';
            if ('\SplFileObject' === $returnType) {
                $content = $response->getBody(); // stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\ExpandResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\ValidationErrorMessageResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\UnauthenticatedResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\ForbiddenResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\PathUnknownErrorMessageResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\AbortedMessageResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\UnprocessableContentMessageResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\InternalErrorMessageResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
            }

            throw $e;
        }
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Get the host index.
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * Operation listObjects.
     *
     * List all objects of the given type that the user has a relation with
     *
     * @param string                                $storeId storeId (required)
     * @param \OpenFGA\API\Model\ListObjectsRequest $body    body (required)
     *
     * @throws ApiException             on non-2xx response
     * @throws InvalidArgumentException
     *
     * @return \OpenFGA\API\Model\AbortedMessageResponse|\OpenFGA\API\Model\ForbiddenResponse|\OpenFGA\API\Model\InternalErrorMessageResponse|\OpenFGA\API\Model\ListObjectsResponse|\OpenFGA\API\Model\PathUnknownErrorMessageResponse|\OpenFGA\API\Model\UnauthenticatedResponse|\OpenFGA\API\Model\UnprocessableContentMessageResponse|\OpenFGA\API\Model\ValidationErrorMessageResponse
     */
    public function listObjects($storeId, $body)
    {
        [$response] = $this->listObjectsWithHttpInfo($storeId, $body);

        return $response;
    }

    /**
     * Operation listObjectsAsync.
     *
     * List all objects of the given type that the user has a relation with
     *
     * @param string                                $storeId (required)
     * @param \OpenFGA\API\Model\ListObjectsRequest $body    (required)
     *
     * @throws InvalidArgumentException
     *
     * @return Promise
     */
    public function listObjectsAsync($storeId, $body)
    {
        return $this->listObjectsAsyncWithHttpInfo($storeId, $body)
            ->then(
                static fn ($response) => $response[0],
            );
    }

    /**
     * Operation listObjectsAsyncWithHttpInfo.
     *
     * List all objects of the given type that the user has a relation with
     *
     * @param string                                $storeId (required)
     * @param \OpenFGA\API\Model\ListObjectsRequest $body    (required)
     *
     * @throws InvalidArgumentException
     *
     * @return Promise
     */
    public function listObjectsAsyncWithHttpInfo($storeId, $body)
    {
        $returnType = '\OpenFGA\API\Model\ListObjectsResponse';
        $request = $this->listObjectsRequest($storeId, $body);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                static function ($response) use ($returnType) {
                    if ('\SplFileObject' === $returnType) {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                static function (HttpException $exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $exception->getRequest(), $exception->getResponse(), $exception);
                },
            );
    }

    /**
     * Create request for operation 'listObjects'.
     *
     * @param string                                $storeId (required)
     * @param \OpenFGA\API\Model\ListObjectsRequest $body    (required)
     *
     * @throws InvalidArgumentException
     *
     * @return RequestInterface
     */
    public function listObjectsRequest($storeId, $body)
    {
        // verify the required parameter 'storeId' is set
        if (null === $storeId || (is_array($storeId) && 0 === count($storeId))) {
            throw new InvalidArgumentException('Missing the required parameter $storeId when calling listObjects');
        }
        // verify the required parameter 'body' is set
        if (null === $body || (is_array($body) && 0 === count($body))) {
            throw new InvalidArgumentException('Missing the required parameter $body when calling listObjects');
        }

        $resourcePath = '/stores/{store_id}/list-objects';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // path params
        if (null !== $storeId) {
            $resourcePath = str_replace(
                '{store_id}',
                ObjectSerializer::toPathValue($storeId),
                $resourcePath,
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart,
        );

        // for model (json/xml)
        if (isset($body)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers,
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('POST', $uri, $headers, $httpBody);
    }

    /**
     * Operation listObjectsWithHttpInfo.
     *
     * List all objects of the given type that the user has a relation with
     *
     * @param string                                $storeId (required)
     * @param \OpenFGA\API\Model\ListObjectsRequest $body    (required)
     *
     * @throws ApiException             on non-2xx response
     * @throws InvalidArgumentException
     *
     * @return array of \OpenFGA\API\Model\ListObjectsResponse|\OpenFGA\API\Model\ValidationErrorMessageResponse|\OpenFGA\API\Model\UnauthenticatedResponse|\OpenFGA\API\Model\ForbiddenResponse|\OpenFGA\API\Model\PathUnknownErrorMessageResponse|\OpenFGA\API\Model\AbortedMessageResponse|\OpenFGA\API\Model\UnprocessableContentMessageResponse|\OpenFGA\API\Model\InternalErrorMessageResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function listObjectsWithHttpInfo($storeId, $body)
    {
        $request = $this->listObjectsRequest($storeId, $body);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();

                throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $response->getStatusCode(), (string) $request->getUri()), $request, $response, $e);
            } catch (ClientExceptionInterface $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", $request, null, $e);
            }

            $statusCode = $response->getStatusCode();

            switch ($statusCode) {
                case 200:
                    if ('\OpenFGA\API\Model\ListObjectsResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\ListObjectsResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 400:
                    if ('\OpenFGA\API\Model\ValidationErrorMessageResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\ValidationErrorMessageResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 401:
                    if ('\OpenFGA\API\Model\UnauthenticatedResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\UnauthenticatedResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 403:
                    if ('\OpenFGA\API\Model\ForbiddenResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\ForbiddenResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 404:
                    if ('\OpenFGA\API\Model\PathUnknownErrorMessageResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\PathUnknownErrorMessageResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 409:
                    if ('\OpenFGA\API\Model\AbortedMessageResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\AbortedMessageResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 422:
                    if ('\OpenFGA\API\Model\UnprocessableContentMessageResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\UnprocessableContentMessageResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 500:
                    if ('\OpenFGA\API\Model\InternalErrorMessageResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\InternalErrorMessageResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
            }

            $returnType = '\OpenFGA\API\Model\ListObjectsResponse';
            if ('\SplFileObject' === $returnType) {
                $content = $response->getBody(); // stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\ListObjectsResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\ValidationErrorMessageResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\UnauthenticatedResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\ForbiddenResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\PathUnknownErrorMessageResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\AbortedMessageResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\UnprocessableContentMessageResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\InternalErrorMessageResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
            }

            throw $e;
        }
    }

    /**
     * Operation listUsers.
     *
     * List the users matching the provided filter who have a certain relation to a particular type.
     *
     * @param string                              $storeId storeId (required)
     * @param \OpenFGA\API\Model\ListUsersRequest $body    body (required)
     *
     * @throws ApiException             on non-2xx response
     * @throws InvalidArgumentException
     *
     * @return \OpenFGA\API\Model\AbortedMessageResponse|\OpenFGA\API\Model\ForbiddenResponse|\OpenFGA\API\Model\InternalErrorMessageResponse|\OpenFGA\API\Model\ListUsersResponse|\OpenFGA\API\Model\PathUnknownErrorMessageResponse|\OpenFGA\API\Model\UnauthenticatedResponse|\OpenFGA\API\Model\UnprocessableContentMessageResponse|\OpenFGA\API\Model\ValidationErrorMessageResponse
     */
    public function listUsers($storeId, $body)
    {
        [$response] = $this->listUsersWithHttpInfo($storeId, $body);

        return $response;
    }

    /**
     * Operation listUsersAsync.
     *
     * List the users matching the provided filter who have a certain relation to a particular type.
     *
     * @param string                              $storeId (required)
     * @param \OpenFGA\API\Model\ListUsersRequest $body    (required)
     *
     * @throws InvalidArgumentException
     *
     * @return Promise
     */
    public function listUsersAsync($storeId, $body)
    {
        return $this->listUsersAsyncWithHttpInfo($storeId, $body)
            ->then(
                static fn ($response) => $response[0],
            );
    }

    /**
     * Operation listUsersAsyncWithHttpInfo.
     *
     * List the users matching the provided filter who have a certain relation to a particular type.
     *
     * @param string                              $storeId (required)
     * @param \OpenFGA\API\Model\ListUsersRequest $body    (required)
     *
     * @throws InvalidArgumentException
     *
     * @return Promise
     */
    public function listUsersAsyncWithHttpInfo($storeId, $body)
    {
        $returnType = '\OpenFGA\API\Model\ListUsersResponse';
        $request = $this->listUsersRequest($storeId, $body);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                static function ($response) use ($returnType) {
                    if ('\SplFileObject' === $returnType) {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                static function (HttpException $exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $exception->getRequest(), $exception->getResponse(), $exception);
                },
            );
    }

    /**
     * Create request for operation 'listUsers'.
     *
     * @param string                              $storeId (required)
     * @param \OpenFGA\API\Model\ListUsersRequest $body    (required)
     *
     * @throws InvalidArgumentException
     *
     * @return RequestInterface
     */
    public function listUsersRequest($storeId, $body)
    {
        // verify the required parameter 'storeId' is set
        if (null === $storeId || (is_array($storeId) && 0 === count($storeId))) {
            throw new InvalidArgumentException('Missing the required parameter $storeId when calling listUsers');
        }
        // verify the required parameter 'body' is set
        if (null === $body || (is_array($body) && 0 === count($body))) {
            throw new InvalidArgumentException('Missing the required parameter $body when calling listUsers');
        }

        $resourcePath = '/stores/{store_id}/list-users';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // path params
        if (null !== $storeId) {
            $resourcePath = str_replace(
                '{store_id}',
                ObjectSerializer::toPathValue($storeId),
                $resourcePath,
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart,
        );

        // for model (json/xml)
        if (isset($body)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers,
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('POST', $uri, $headers, $httpBody);
    }

    /**
     * Operation listUsersWithHttpInfo.
     *
     * List the users matching the provided filter who have a certain relation to a particular type.
     *
     * @param string                              $storeId (required)
     * @param \OpenFGA\API\Model\ListUsersRequest $body    (required)
     *
     * @throws ApiException             on non-2xx response
     * @throws InvalidArgumentException
     *
     * @return array of \OpenFGA\API\Model\ListUsersResponse|\OpenFGA\API\Model\ValidationErrorMessageResponse|\OpenFGA\API\Model\UnauthenticatedResponse|\OpenFGA\API\Model\ForbiddenResponse|\OpenFGA\API\Model\PathUnknownErrorMessageResponse|\OpenFGA\API\Model\AbortedMessageResponse|\OpenFGA\API\Model\UnprocessableContentMessageResponse|\OpenFGA\API\Model\InternalErrorMessageResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function listUsersWithHttpInfo($storeId, $body)
    {
        $request = $this->listUsersRequest($storeId, $body);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();

                throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $response->getStatusCode(), (string) $request->getUri()), $request, $response, $e);
            } catch (ClientExceptionInterface $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", $request, null, $e);
            }

            $statusCode = $response->getStatusCode();

            switch ($statusCode) {
                case 200:
                    if ('\OpenFGA\API\Model\ListUsersResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\ListUsersResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 400:
                    if ('\OpenFGA\API\Model\ValidationErrorMessageResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\ValidationErrorMessageResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 401:
                    if ('\OpenFGA\API\Model\UnauthenticatedResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\UnauthenticatedResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 403:
                    if ('\OpenFGA\API\Model\ForbiddenResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\ForbiddenResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 404:
                    if ('\OpenFGA\API\Model\PathUnknownErrorMessageResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\PathUnknownErrorMessageResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 409:
                    if ('\OpenFGA\API\Model\AbortedMessageResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\AbortedMessageResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 422:
                    if ('\OpenFGA\API\Model\UnprocessableContentMessageResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\UnprocessableContentMessageResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 500:
                    if ('\OpenFGA\API\Model\InternalErrorMessageResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\InternalErrorMessageResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
            }

            $returnType = '\OpenFGA\API\Model\ListUsersResponse';
            if ('\SplFileObject' === $returnType) {
                $content = $response->getBody(); // stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\ListUsersResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\ValidationErrorMessageResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\UnauthenticatedResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\ForbiddenResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\PathUnknownErrorMessageResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\AbortedMessageResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\UnprocessableContentMessageResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\InternalErrorMessageResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
            }

            throw $e;
        }
    }

    /**
     * Set the host index.
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Operation streamedListObjects.
     *
     * Stream all objects of the given type that the user has a relation with
     *
     * @param string                                $storeId storeId (required)
     * @param \OpenFGA\API\Model\ListObjectsRequest $body    body (required)
     *
     * @throws ApiException             on non-2xx response
     * @throws InvalidArgumentException
     *
     * @return \OpenFGA\API\Model\AbortedMessageResponse|\OpenFGA\API\Model\ForbiddenResponse|\OpenFGA\API\Model\InternalErrorMessageResponse|\OpenFGA\API\Model\PathUnknownErrorMessageResponse|\OpenFGA\API\Model\StreamResultOfStreamedListObjectsResponse|\OpenFGA\API\Model\UnauthenticatedResponse|\OpenFGA\API\Model\UnprocessableContentMessageResponse|\OpenFGA\API\Model\ValidationErrorMessageResponse
     */
    public function streamedListObjects($storeId, $body)
    {
        [$response] = $this->streamedListObjectsWithHttpInfo($storeId, $body);

        return $response;
    }

    /**
     * Operation streamedListObjectsAsync.
     *
     * Stream all objects of the given type that the user has a relation with
     *
     * @param string                                $storeId (required)
     * @param \OpenFGA\API\Model\ListObjectsRequest $body    (required)
     *
     * @throws InvalidArgumentException
     *
     * @return Promise
     */
    public function streamedListObjectsAsync($storeId, $body)
    {
        return $this->streamedListObjectsAsyncWithHttpInfo($storeId, $body)
            ->then(
                static fn ($response) => $response[0],
            );
    }

    /**
     * Operation streamedListObjectsAsyncWithHttpInfo.
     *
     * Stream all objects of the given type that the user has a relation with
     *
     * @param string                                $storeId (required)
     * @param \OpenFGA\API\Model\ListObjectsRequest $body    (required)
     *
     * @throws InvalidArgumentException
     *
     * @return Promise
     */
    public function streamedListObjectsAsyncWithHttpInfo($storeId, $body)
    {
        $returnType = '\OpenFGA\API\Model\StreamResultOfStreamedListObjectsResponse';
        $request = $this->streamedListObjectsRequest($storeId, $body);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                static function ($response) use ($returnType) {
                    if ('\SplFileObject' === $returnType) {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                },
                static function (HttpException $exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();

                    throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $exception->getRequest(), $exception->getResponse(), $exception);
                },
            );
    }

    /**
     * Create request for operation 'streamedListObjects'.
     *
     * @param string                                $storeId (required)
     * @param \OpenFGA\API\Model\ListObjectsRequest $body    (required)
     *
     * @throws InvalidArgumentException
     *
     * @return RequestInterface
     */
    public function streamedListObjectsRequest($storeId, $body)
    {
        // verify the required parameter 'storeId' is set
        if (null === $storeId || (is_array($storeId) && 0 === count($storeId))) {
            throw new InvalidArgumentException('Missing the required parameter $storeId when calling streamedListObjects');
        }
        // verify the required parameter 'body' is set
        if (null === $body || (is_array($body) && 0 === count($body))) {
            throw new InvalidArgumentException('Missing the required parameter $body when calling streamedListObjects');
        }

        $resourcePath = '/stores/{store_id}/streamed-list-objects';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // path params
        if (null !== $storeId) {
            $resourcePath = str_replace(
                '{store_id}',
                ObjectSerializer::toPathValue($storeId),
                $resourcePath,
            );
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart,
        );

        // for model (json/xml)
        if (isset($body)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem,
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers,
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('POST', $uri, $headers, $httpBody);
    }

    /**
     * Operation streamedListObjectsWithHttpInfo.
     *
     * Stream all objects of the given type that the user has a relation with
     *
     * @param string                                $storeId (required)
     * @param \OpenFGA\API\Model\ListObjectsRequest $body    (required)
     *
     * @throws ApiException             on non-2xx response
     * @throws InvalidArgumentException
     *
     * @return array of \OpenFGA\API\Model\StreamResultOfStreamedListObjectsResponse|\OpenFGA\API\Model\ValidationErrorMessageResponse|\OpenFGA\API\Model\UnauthenticatedResponse|\OpenFGA\API\Model\ForbiddenResponse|\OpenFGA\API\Model\PathUnknownErrorMessageResponse|\OpenFGA\API\Model\AbortedMessageResponse|\OpenFGA\API\Model\UnprocessableContentMessageResponse|\OpenFGA\API\Model\InternalErrorMessageResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function streamedListObjectsWithHttpInfo($storeId, $body)
    {
        $request = $this->streamedListObjectsRequest($storeId, $body);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();

                throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $response->getStatusCode(), (string) $request->getUri()), $request, $response, $e);
            } catch (ClientExceptionInterface $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", $request, null, $e);
            }

            $statusCode = $response->getStatusCode();

            switch ($statusCode) {
                case 200:
                    if ('\OpenFGA\API\Model\StreamResultOfStreamedListObjectsResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\StreamResultOfStreamedListObjectsResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 400:
                    if ('\OpenFGA\API\Model\ValidationErrorMessageResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\ValidationErrorMessageResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 401:
                    if ('\OpenFGA\API\Model\UnauthenticatedResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\UnauthenticatedResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 403:
                    if ('\OpenFGA\API\Model\ForbiddenResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\ForbiddenResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 404:
                    if ('\OpenFGA\API\Model\PathUnknownErrorMessageResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\PathUnknownErrorMessageResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 409:
                    if ('\OpenFGA\API\Model\AbortedMessageResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\AbortedMessageResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 422:
                    if ('\OpenFGA\API\Model\UnprocessableContentMessageResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\UnprocessableContentMessageResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
                case 500:
                    if ('\OpenFGA\API\Model\InternalErrorMessageResponse' === '\SplFileObject') {
                        $content = $response->getBody(); // stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenFGA\API\Model\InternalErrorMessageResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                    ];
            }

            $returnType = '\OpenFGA\API\Model\StreamResultOfStreamedListObjectsResponse';
            if ('\SplFileObject' === $returnType) {
                $content = $response->getBody(); // stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders(),
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\StreamResultOfStreamedListObjectsResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\ValidationErrorMessageResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\UnauthenticatedResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\ForbiddenResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\PathUnknownErrorMessageResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\AbortedMessageResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\UnprocessableContentMessageResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenFGA\API\Model\InternalErrorMessageResponse',
                        $e->getResponseHeaders(),
                    );
                    $e->setResponseObject($data);

                    break;
            }

            throw $e;
        }
    }

    /**
     * @param string                      $method
     * @param string|UriInterface         $uri
     * @param array                       $headers
     * @param null|StreamInterface|string $body
     *
     * @return RequestInterface
     */
    private function createRequest(string $method, $uri, array $headers = [], $body = null): RequestInterface
    {
        if ($this->requestFactory instanceof RequestFactory) {
            return $this->requestFactory->createRequest(
                $method,
                $uri,
                $headers,
                $body,
            );
        }

        if (is_string($body) && '' !== $body && null === $this->streamFactory) {
            throw new RuntimeException('Cannot create request: A stream factory is required to create a request with a non-empty string body.');
        }

        $request = $this->requestFactory->createRequest($method, $uri);

        foreach ($headers as $key => $value) {
            $request = $request->withHeader($key, $value);
        }

        if (null !== $body && '' !== $body) {
            $request = $request->withBody(
                is_string($body) ? $this->streamFactory->createStream($body) : $body,
            );
        }

        return $request;
    }

    private function createUri(
        string $operationHost,
        string $resourcePath,
        array $queryParams,
    ): UriInterface {
        $parsedUrl = parse_url($operationHost);

        $host = $parsedUrl['host'] ?? null;
        $scheme = $parsedUrl['scheme'] ?? null;
        $basePath = $parsedUrl['path'] ?? null;
        $port = $parsedUrl['port'] ?? null;
        $user = $parsedUrl['user'] ?? null;
        $password = $parsedUrl['pass'] ?? null;

        $uri = $this->uriFactory->createUri($basePath . $resourcePath)
            ->withHost($host)
            ->withScheme($scheme)
            ->withPort($port)
            ->withQuery(ObjectSerializer::buildQuery($queryParams));

        if ($user) {
            $uri = $uri->withUserInfo($user, $password);
        }

        return $uri;
    }
}
