<?php

declare(strict_types=1);
/**
 * Userset.
 *
 * PHP version 7.4
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 */

/**
 * OpenFGA.
 *
 * A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
 *
 * The version of the OpenAPI document: 1.x
 * Contact: community@openfga.dev
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenFGA\API\Models;

use ArrayAccess;
use InvalidArgumentException;
use JsonSerializable;
use OpenFGA\API\ObjectSerializer;
use ReturnTypeWillChange;

use function array_key_exists;
use function count;
use function in_array;

/**
 * Userset Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @link     https://openapi-generator.tech
 *
 * @implements \ArrayAccess<string, mixed>
 */
final class Userset implements ArrayAccess, JsonSerializable, ModelInterface
{
    public const DISCRIMINATOR = null;

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    private $container = [];

    /**
     * If a nullable field gets set to null, insert it here.
     *
     * @var bool[]
     */
    private array $openAPINullablesSetToNull = [];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    private static $attributeMap = [
        'this' => 'this',
        'computed_userset' => 'computedUserset',
        'tuple_to_userset' => 'tupleToUserset',
        'union' => 'union',
        'intersection' => 'intersection',
        'difference' => 'difference',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    private static $getters = [
        'this' => 'getThis',
        'computed_userset' => 'getComputedUserset',
        'tuple_to_userset' => 'getTupleToUserset',
        'union' => 'getUnion',
        'intersection' => 'getIntersection',
        'difference' => 'getDifference',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    private static $openAPIFormats = [
        'this' => null,
        'computed_userset' => null,
        'tuple_to_userset' => null,
        'union' => null,
        'intersection' => null,
        'difference' => null,
    ];

    /**
     * The original name of the model.
     *
     * @var string
     */
    private static $openAPIModelName = 'Userset';

    /**
     * Array of nullable properties. Used for (de)serialization.
     *
     * @var bool[]
     */
    private static array $openAPINullables = [
        'this' => false,
        'computed_userset' => false,
        'tuple_to_userset' => false,
        'union' => false,
        'intersection' => false,
        'difference' => false,
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    private static $openAPITypes = [
        'this' => 'object',
        'computed_userset' => '\OpenFGA\API\Models\ObjectRelation',
        'tuple_to_userset' => '\OpenFGA\API\Models\V1TupleToUserset',
        'union' => '\OpenFGA\API\Models\Usersets',
        'intersection' => '\OpenFGA\API\Models\Usersets',
        'difference' => '\OpenFGA\API\Models\V1Difference',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    private static $setters = [
        'this' => 'setThis',
        'computed_userset' => 'setComputedUserset',
        'tuple_to_userset' => 'setTupleToUserset',
        'union' => 'setUnion',
        'intersection' => 'setIntersection',
        'difference' => 'setDifference',
    ];

    /**
     * Constructor.
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('this', $data ?? [], null);
        $this->setIfExists('computed_userset', $data ?? [], null);
        $this->setIfExists('tuple_to_userset', $data ?? [], null);
        $this->setIfExists('union', $data ?? [], null);
        $this->setIfExists('intersection', $data ?? [], null);
        $this->setIfExists('difference', $data ?? [], null);
    }

    /**
     * Gets the string presentation of the object.
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT,
        );
    }

    /**
     * Gets computed_userset.
     *
     * @return null|ObjectRelation
     */
    public function getComputedUserset()
    {
        return $this->container['computed_userset'];
    }

    /**
     * Gets difference.
     *
     * @return null|V1Difference
     */
    public function getDifference()
    {
        return $this->container['difference'];
    }

    /**
     * Gets intersection.
     *
     * @return null|Usersets
     */
    public function getIntersection()
    {
        return $this->container['intersection'];
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    /**
     * Gets this.
     *
     * @return null|object
     */
    public function getThis()
    {
        return $this->container['this'];
    }

    /**
     * Gets tuple_to_userset.
     *
     * @return null|V1TupleToUserset
     */
    public function getTupleToUserset()
    {
        return $this->container['tuple_to_userset'];
    }

    /**
     * Gets union.
     *
     * @return null|Usersets
     */
    public function getUnion()
    {
        return $this->container['union'];
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     *
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        return [];
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     *
     * @return bool
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return null|mixed
     */
    #[ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param null|int $offset Offset
     * @param mixed    $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (null === $offset) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Sets computed_userset.
     *
     * @param null|ObjectRelation $computed_userset computed_userset
     *
     * @return self
     */
    public function setComputedUserset($computed_userset)
    {
        if (null === $computed_userset) {
            throw new InvalidArgumentException('non-nullable computed_userset cannot be null');
        }
        $this->container['computed_userset'] = $computed_userset;

        return $this;
    }

    /**
     * Sets difference.
     *
     * @param null|V1Difference $difference difference
     *
     * @return self
     */
    public function setDifference($difference)
    {
        if (null === $difference) {
            throw new InvalidArgumentException('non-nullable difference cannot be null');
        }
        $this->container['difference'] = $difference;

        return $this;
    }

    /**
     * Sets intersection.
     *
     * @param null|Usersets $intersection intersection
     *
     * @return self
     */
    public function setIntersection($intersection)
    {
        if (null === $intersection) {
            throw new InvalidArgumentException('non-nullable intersection cannot be null');
        }
        $this->container['intersection'] = $intersection;

        return $this;
    }

    /**
     * Sets this.
     *
     * @param null|object $this A DirectUserset is a sentinel message for referencing the direct members specified by an object/relation mapping.
     *
     * @return self
     */
    public function setThis($this)
    {
        if (null === $this) {
            throw new InvalidArgumentException('non-nullable this cannot be null');
        }
        $this->container['this'] = $this;

        return $this;
    }

    /**
     * Sets tuple_to_userset.
     *
     * @param null|V1TupleToUserset $tuple_to_userset tuple_to_userset
     *
     * @return self
     */
    public function setTupleToUserset($tuple_to_userset)
    {
        if (null === $tuple_to_userset) {
            throw new InvalidArgumentException('non-nullable tuple_to_userset cannot be null');
        }
        $this->container['tuple_to_userset'] = $tuple_to_userset;

        return $this;
    }

    /**
     * Sets union.
     *
     * @param null|Usersets $union union
     *
     * @return self
     */
    public function setUnion($union)
    {
        if (null === $union) {
            throw new InvalidArgumentException('non-nullable union cannot be null');
        }
        $this->container['union'] = $union;

        return $this;
    }

    /**
     * Gets a header-safe presentation of the object.
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return 0 === count($this->listInvalidProperties());
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * Checks if a property is nullable.
     *
     * @param string $property
     *
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of nullable field names deliberately set to null.
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array.
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && null === $fields[$variableName]) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null.
     *
     * @param bool[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Array of nullable properties.
     *
     * @return array
     */
    private static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }
}
