name: Generate SBOM

on:
  push:
    branches: [ main ]
    paths:
      - 'composer.json'
      - 'composer.lock'
  pull_request:
    branches: [ main ]
    paths:
      - 'composer.json'
      - 'composer.lock'
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to upload artifacts to releases
      packages: write # Needed for SBOM upload to GitHub packages

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: composer install --no-dev --no-interaction --prefer-dist

      - name: Generate CycloneDX SBOM
        uses: CycloneDX/gh-php-composer-generate-sbom@v2
        with:
          path: .
          output: sbom.cyclonedx.json
          composer-path: composer
          
      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.cyclonedx.json
          retention-days: 30

      # Only upload SBOM to releases when a release is created
      - name: Upload SBOM to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sbom.cyclonedx.json
          asset_name: openfga-php-sbom.cyclonedx.json
          tag: ${{ github.ref }}
          overwrite: true
