name: Scorecard Analysis
on:
  branch_protection_rule:
  schedule:
    - cron: "20 7 * * 2"
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  analysis:
    name: Scorecard
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: "Run analysis"
        uses: ossf/scorecard-action@v2.3.1
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.SCORECARD_TOKEN }}
          publish_results: true

      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5
