name: "Security: SBOM"

on:
  push:
    branches: [main]
    paths:
      - composer.json
      - composer.lock
  pull_request:
    branches: [main]
    paths:
      - composer.json
      - composer.lock
  release:
    types: [created]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: "Generate Report"
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to upload artifacts to releases
      packages: write # Needed for SBOM upload to GitHub packages

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup PHP
        uses: shivammathur/setup-php@ec406be512d7077f68eed36e63f4d91bc006edc4 # 2.35.4
        with:
          php-version: "8.3"
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: composer install --no-dev --no-interaction --prefer-dist

      - name: Install SBOM composer plugin
        run: |-
          composer global config --no-plugins allow-plugins.cyclonedx/cyclonedx-php-composer true
          composer global require cyclonedx/cyclonedx-php-composer

      - name: Generate SBOM
        run: composer cyclonedx:make-sbom --output-format=JSON --output-file=sbom.cyclonedx.json

      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: sbom
          path: sbom.cyclonedx.json
          retention-days: 30

      # Only upload SBOM to releases when a release is created
      - name: Upload SBOM to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@81c65b7cd4de9b2570615ce3aad67a41de5b1a13 # 2.11.2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sbom.cyclonedx.json
          asset_name: openfga-php-sbom.cyclonedx.json
          tag: ${{ github.ref }}
          overwrite: true
