name: "Test: API Contract"

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 0"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  contract:
    name: "OpenAPI Specification"
    runs-on: ubuntu-latest

    env:
      OPENFGA_API_COMMIT: ${{ vars.OPENFGA_API_COMMIT || 'main' }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup PHP
        uses: shivammathur/setup-php@20529878ed81ef8e78ddf08b480401e6101a850f # 2.35.3
        with:
          php-version: "8.3"
          extensions: dom, curl, libxml, mbstring, zip, fileinfo
          ini-values: error_reporting=E_ALL, memory_limit=2G
          coverage: pcov
          tools: composer:v2

      - name: Install dependencies
        run: composer update --prefer-stable --no-interaction --no-progress --ansi

      - name: Run contract tests
        run: composer test:contract

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: contract

      - name: Upload test results to Codecov
        uses: codecov/test-results-action@47f89e9acb64b76debcd5ea40642d25a4adced9f # v1.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: contract
