name: "Test: API Contract"

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 0"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  contract:
    name: "OpenAPI Specification"
    runs-on: ubuntu-latest

    env:
      OPENFGA_API_COMMIT: ${{ vars.OPENFGA_API_COMMIT || 'main' }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup PHP
        uses: shivammathur/setup-php@ec406be512d7077f68eed36e63f4d91bc006edc4 # 2.35.4
        with:
          php-version: "8.3"
          extensions: dom, curl, libxml, mbstring, zip, fileinfo
          ini-values: error_reporting=E_ALL, memory_limit=2G
          coverage: pcov
          tools: composer:v2

      - name: Install dependencies
        run: composer update --prefer-stable --no-interaction --no-progress --ansi

      - name: Run contract tests
        run: composer test:contract

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: contract

      - name: Upload test results to Codecov
        uses: codecov/test-results-action@47f89e9acb64b76debcd5ea40642d25a4adced9f # v1.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: contract
